version: "3.9"
services:
  app:
    container_name: app-container
    build: .
    ports:
      - "9090:8080"
    restart: always
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/users_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-db
  db:
    container_name: db-container
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_app
    ports:
      - "3306:3306"
    networks:
      - app-db
networks:
 app-db: